config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resource :event_participant, only: [ :create, :destroy ]
    resources :event_songs, only: [ :create, :destroy ]
    resources :comments, only: [ :create ]
  end

  resources :songs do
    resources :ratings, only: [ :create ], shallow: true
  end

  namespace :admin do
    resources :users do
      member do
        get "impersonate"
      end
    end
    resources :events
  end

get "stop_impersonating", to: "admin/users#stop_impersonating", as: :stop_impersonating
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500. змінити пароль через фор
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
end

app/views/shared/_buttons.html.erb
<% if current_user %>
  <% if current_user.event_participants.exists?(event_id: @event.id) %>
    <%= button_to 'Leave Event', event_event_participant_path(@event),
        method: :delete,
        class: "btn btn__blue",
        form: { data: { turbo: false } } %>
  <% else %>
    <%= button_to 'Join Event', event_event_participant_path(@event),
        method: :post,
        class: "btn btn__blue",
        form: { data: { turbo: false } } %>
  <% end %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-message <%= flash_class(type) %> flash-msg-wrap mt-16">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer aria-label="SoulShare Footer" class="bg-white p-6 w-full fixed bottom-0 shadow-md border border-gray-200">
  <div class="container mx-auto px-4 flex flex-col sm:flex-row justify-between items-center sm:items-start gap-y-4 text-sm text-gray-600">
    <div class="flex gap-4 text-lg text-center sm:text-left">
      <%= link_to "Home", root_path, class: "hover:text-sky-800 transition" %>
      <%= link_to "Events", events_path, class: "hover:text-sky-800 transition" %>
      <%= link_to "Songs", songs_path, class: "hover:text-sky-800 transition" %>
    </div>

    <p class="text-center text-sm text-gray-500 sm:text-left">
      &copy; <%= Time.current.year %>. All rights reserved.
    </p>

    <ul class="flex justify-center sm:justify-start gap-6">
      <li>
        <a href="#" rel="noreferrer" target="_blank" class="transition hover:opacity-75">
          <%= inline_svg "icons/facebook.svg", class: "h-6 w-6 text-sky-700 hover:text-sky-700/75" %>
        </a>
      </li>

      <li>
        <a href="#" rel="noreferrer" target="_blank" class="transition hover:opacity-75">
          <%= inline_svg "icons/instagram.svg", class: "h-6 w-6 text-sky-700 hover:text-sky-700/75" %>
        </a>
      </li>

      <li>
        <a href="#" rel="noreferrer" target="_blank" class="transition hover:opacity-75">
          <%= inline_svg "icons/twitter.svg", class: "h-6 w-6 text-sky-700 hover:text-sky-700/75" %>
        </a>
      </li>

      <li>
        <a href="#" rel="noreferrer" target="_blank" class="transition hover:opacity-75">
          <%= inline_svg "icons/github.svg", class: "h-6 w-6 text-sky-700 hover:text-sky-700/75" %>
        </a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="fixed w-full top-0 z-50">
  <nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 py-3 flex justify-between items-center">
      <!-- Логотип -->
      <div class="text-3xl font-bold text-violet-600">
        <%= link_to "SoulShare", root_path, class: "hover:text-indigo-800" %>
      </div>
      <!-- Навігація -->
      <div class="space-x-6 text-gray-700 font-medium">
        <%= link_to "Events", events_path, class: "hover:text-indigo-600 transition" %>
        <%= link_to "Songs", songs_path, class: "hover:text-indigo-600 transition" %>
        <% if current_user&.admin? %>
          <%= link_to "Admin", admin_users_path, class: "hover:text-indigo-600 transition" %>
        <% end %>
      </div>
      <% if session[:impersonated_user_id] %>
        <%= link_to 'Stop Impersonating', stop_impersonating_path, method: :delete, class: 'btn btn__pink' %>
      <% end %>
      <!-- Кнопка логіну / профілю -->
      <div class="flex gap-2">
        <% if user_signed_in? %>
          <%= link_to edit_user_registration_path, class: "profile__link flex items-center space-x-2" do %>
            <%= image_tag("profile.png", alt: "Profile", class: "w-5 h-5") %>
            <span><%= current_user.name || "Profile" %></span>
          <% end %>

          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn__logout" %>
        <% else %>
        <div class="flex gap-2">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn__secondary' %>
          <%= link_to "Login", new_user_session_path, class: "btn btn__primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </nav>
</header> 