config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resource :event_participant, only: [ :create, :destroy ]
    resources :event_songs, only: [ :create, :destroy ]
    resources :comments, only: [ :create ]
  end

  resources :songs do
    resources :ratings, only: [ :create ], shallow: true
  end

  namespace :admin do
    resources :users do
      member do
        get "impersonate"
      end
    end
    resources :events
  end

get "stop_impersonating", to: "admin/users#stop_impersonating", as: :stop_impersonating
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500. змінити пароль через фор
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :created_by, class_name: "User", required: true
  belongs_to :location, optional: true
  has_many :event_participants, dependent: :destroy
  has_many :event_songs, dependent: :destroy
  has_many :songs, through: :event_songs
  has_many :comments, through: :event_participants

  validates :created_by, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @events = collection
  end

  def show
    @event = resources
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_events_path, notice: "Event created successfully"
    else
      render :new
    end
  end

  def edit
    @event = resource
  end

  def update
    @event = resource
    if @event.update(event_params)
      redirect_to admin_events_path, notice: "Event updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @event = resource
    @event.destroy
    redirect_to admin_events_path, notice: "Event deleted successfully"
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :location)
  end

    def collection
    Event.all
  end

  def resource
    Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:query].present?
      search_results = EventIndex.query(multi_match: {
        query: params[:query],
        fields: %w[title description]
      })

      event_ids = search_results.map(&:id)
      @events = Event.where(id: event_ids)
    else
      @events = collection
    end
  end

  def show
    @event = resource
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = resource
  end

  def update
    @event = resource
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = resource
    @event.destroy
    redirect_to events_path, notice: "Event was successfully deleted."
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location_id, :start_at, :end_at)
  end

  def collection
    Event.all
  end

  def resource
    Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container flex justify-center">
  <div class="form-container">
    <% if event.errors.any? %>
      <div class="bg-red-300 text-red-800 p-4 rounded mb-4">
        <h3 class="font-bold"><%= pluralize(event.errors.count, "error") %> can't save event:</h3>
        <ul class="list-disc ml-5">
          <% event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: event, local: true, class: "space-y-4") do |f| %>
      <div>
        <%= f.label :title, class: "form__label" %>
        <%= f.text_field :title, class: "form__input" %>
      </div>

      <div>
        <%= f.label :description, class: "form__label" %>
        <%= f.text_area :description, class: "form__input" %>
      </div>

      <div>
        <%= f.label :location_id, "Location", class: "form__label" %>
        <%= f.collection_select :location_id, Location.all, :id, :name, { prompt: "Select a location" }, class: "form__input" %>
      </div>

      <div>
        <%= f.label :start_at, "Start time", class: "form__label"  %>
        <%= f.datetime_select :start_at, class: "w-full p-2 border rounded" %>
      </div>

      <div>
        <%= f.label :end_at, "End time", class: "form__label" %>
        <%= f.datetime_select :end_at, class: "w-full p-2 border rounded" %>
      </div>

      <%= f.submit class: "btn btn__primary" %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="container mb-20">
  <div class="mb-6">
    <%= form_with url: events_path, method: :get, local: true, class: "flex items-center gap-4" do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search events...", class: "search__input" %>
      <%= button_tag "Search", type: "submit", class: "btn btn__blue" %>
      <% if params[:query].present? %>
        <%= link_to "Clear", events_path, class: "btn btn__secondary" %>
      <% end %>
    <% end %>
  </div>
  <h1 class="text-2xl font-bold mb-4">Events</h1>

  <%= link_to "+ New Event", new_event_path, class: "btn btn__pink" %>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-6">
    <% @events.each do |event| %>
      <div class="bg-white rounded-2xl shadow p-6 hover:shadow-lg transition relative">
      <!-- Статус івенту: open або closed -->
        <% if event.start_at.present? %>
            <% if event.start_at.to_date > Date.today %>
              <div class="badge bg-green-600 absolute bottom-6 right-6">Open</div>
            <% else %>
              <div class="badge bg-red-600 absolute bottom-6 right-6">Closed</div>
            <% end %>
        <% end %>

        <%= image_tag("music.jpg", alt: "Event", class: "w-full h-40 object-cover rounded-xl mb-4") %>
        <%= link_to event_path(event), class: "block space-y-2" do %>
          <h2 class="text-xl font-bold text-indigo-600 hover:underline">
            <%= event.title %>
          </h2>
          <p class="text-gray-700"><%= event.description.truncate(100) %></p>
          <div class="text-sm text-gray-600 flex items-center gap-2">
            <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#8d3db8"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="0.048"></g><g id="SVGRepo_iconCarrier"> <path d="M12 21C15.5 17.4 19 14.1764 19 10.2C19 6.22355 15.866 3 12 3C8.13401 3 5 6.22355 5 10.2C5 14.1764 8.5 17.4 12 21Z" stroke="#8d3db8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12 12C13.1046 12 14 11.1046 14 10C14 8.89543 13.1046 8 12 8C10.8954 8 10 8.89543 10 10C10 11.1046 10.8954 12 12 12Z" stroke="#8d3db8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
            <%= event.location&.city || "No location" %>
          </div>
          <div class="text-sm text-gray-600 flex items-center gap-2">
            <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M3 9H21M7 3V5M17 3V5M6 13H8M6 17H8M11 13H13M11 17H13M16 13H18M16 17H18M6.2 21H17.8C18.9201 21 19.4802 21 19.908 20.782C20.2843 20.5903 20.5903 20.2843 20.782 19.908C21 19.4802 21 18.9201 21 17.8V8.2C21 7.07989 21 6.51984 20.782 6.09202C20.5903 5.71569 20.2843 5.40973 19.908 5.21799C19.4802 5 18.9201 5 17.8 5H6.2C5.0799 5 4.51984 5 4.09202 5.21799C3.71569 5.40973 3.40973 5.71569 3.21799 6.09202C3 6.51984 3 7.07989 3 8.2V17.8C3 18.9201 3 19.4802 3.21799 19.908C3.40973 20.2843 3.71569 20.5903 4.09202 20.782C4.51984 21 5.07989 21 6.2 21Z" stroke="#8d3db8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
            <%= event.start_at&.strftime("%d %b %Y, %H:%M") || "Time TBD" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form", event: @event %>

app/views/events/show.html.erb
<div class="container max-w-3xl mx-auto p-10 bg-white rounded-xl shadow mb-24">
  <h1 class="text-3xl font-bold text-gray-800 mb-4"><%= @event.title %></h1>
  <p class="text-gray-600 mb-4"><%= @event.description %></p>

<!-- Локація і час -->
  <div class="title">Location:
    <span class="text-gray-700 font-normal">
      <% if @event.location.present? %>
        <%= [@event.location.name, @event.location.address, @event.location.city].compact.join(", ") %>
        <% else %>
          -
      <% end %>
    </span>
  </div>
  <div class="title">Start:
    <span class="text-gray-700 font-normal"><%= @event.start_at&.strftime("%d.%m.%Y %H:%M") || "Not specified" %></span>
  </div>
  <div class="title">End:
    <span class="text-gray-700 font-normal"><%= @event.end_at&.strftime("%d.%m.%Y %H:%M") || "Not specified" %></span>
  </div>

<!-- Статус івенту: open або closed -->
  <% if @event.start_at.present? %>
    <div class="title">Status:
      <% if @event.start_at.to_date > Date.today %>
        <span class="badge bg-green-600">Open</span>
      <% else %>
        <span class="badge bg-red-500">Closed</span>
      <% end %>
    </div>
  <% end %>

<!-- Кнопки редагування, видалення, повернення та приєднання до івенту -->
  <div class="flex gap-4 pt-4 mb-4">
    <%= link_to "Edit", edit_event_path(@event), class: "btn btn__primary" %>
    <%= button_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?"  }, class: "btn btn__pink" %>
    <%= link_to "Back", events_path, class: "btn btn__secondary" %>

    <%= render 'shared/buttons' %>
  </div>

  <!-- song list -->
  <div class="mb-4">
    <h3 class="text-lg font-bold mb-2">Songs in this event:</h3>
    <ul>
      <% @event.songs.each do |song| %>
        <li class="flex items-center justify-between p-2 border">
          <div class="flex items-center gap-4">
          <%= inline_svg "icons/song.svg", class: "h-6 w-6" %>
          <%= link_to song.title, song_path(song), class: "text-blue-500 hover:text-blue-700" %> 
          </div>
          <%= button_to "Remove", event_event_song_path(@event, song), method: :delete, data: { confirm: "Are you sure?" }, class: "btn__pink " %>
        </li>
      <% end %>
    </ul>
  </div>
  <div>
    <h4 class="text-lg font-bold mb-2">Add song to event:</h4>      
      <%= form_with url: event_event_songs_path(@event), method: :post, local: true do |f| %>
        <div class="flex items-center justify-between"> 
          <%= select_tag :song_id, options_from_collection_for_select(Song.all, :id, :title), class: "form__input w-1/2" %>
          <%= f.submit "Add", class: "btn btn__secondary mb-4" %>
        </div>
      <% end %>    
  </div>

  <!-- учасники -->
  <% if current_user&.admin? %>
    <h3 class="text-lg font-bold mb-2">Participants:</h3>
    <ul class="mb-4">
      <% @event.event_participants.includes(:user).each do |participant| %>
        <li class="mb-2 flex items-center gap-4">
          <%= image_tag("profile.png", alt: "Profile", class: "w-5 h-5") %>
          <%= participant.user.name %> 
          <span class="text-gray-400">
            (<%= participant.user.email %>)
          </span>
        </li>
      <% end %>
    </ul>
  <% end %>
<h4 class="text-lg font-bold mb-2">Comments</h4>

<div id="comments">
  <turbo-frame id="comments_list">
    <%= render @event.comments %>
  </turbo-frame>
</div>

<div id="comment_form_container">
  <%= render 'comments/form', event: @event, comment: @event.comments.build %>
</div>

<div id="comment_errors"></div>
  
</div>