config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resource :event_participant, only: [ :create, :destroy ]
    resources :event_songs, only: [ :create, :destroy ]
    resources :comments, only: [ :create ]
  end

  resources :songs do
    resources :ratings, only: [ :create ], shallow: true
  end

  namespace :admin do
    resources :users do
      member do
        get "impersonate"
      end
    end
    resources :events
  end

get "stop_impersonating", to: "admin/users#stop_impersonating", as: :stop_impersonating
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500. змінити пароль через фор
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :added_by, class_name: "User", foreign_key: "added_by_id"
  has_many :event_songs
  has_many :events, through: :event_songs
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy

  def average_rating
    ratings.average(:rating)&.round(1)
  end

  validates :title, presence: true, length: { maximum: 255 }
  validates :author, presence: true, length: { maximum: 255 }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      search_results = SongIndex.query(multi_match: {
        query: params[:query],
        fields: %w[title author genre lyrics]
      })

      song_ids = search_results.map(&:id)
      @songs = Song.where(id: song_ids)
    else
      @songs = collection
    end
  end

  def show
    @song = resource
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.added_by = current_user

    if @song.save
      redirect_to songs_path, notice: "Song created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @song = resource
  end

  def update
    @song = resource
    if @song.update(song_params)
      redirect_to song_path(@song), notice: "Song updated successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @song = resource
    @song.destroy
    redirect_to songs_path, notice: "Song deleted successfully!"
  end

  private

  def collection
    Song.all
  end

  def resource
    Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :author, :genre, :lyrics)
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<div class="container flex justify-center pb-20">
  <div class="form-container">
    <% if @song.errors.any? %>
      <div class="bg-red-300 text-red-800 p-4 rounded mb-4">
        <h3 class="font-bold"><%= pluralize(@song.errors.count, "error") %> can't save songs:</h3>
        <ul class="list-disc ml-5">
          <% @song.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @song, local: false do |f| %>
      <div>
        <%= f.label :title, "Song Title", class: "form__label" %>
        <%= f.text_field :title, class: "form__input" %>
      </div>

      <div>
        <%= f.label :author, "Author", class: "form__label" %>
        <%= f.text_field :author, class: "form__input" %>
      </div>

      <div>
        <%= f.label :genre, "Genre", class: "form__label" %>
        <%= f.text_field :genre, class: "form__input" %>
      </div>

      <div>
        <%= f.label :lyrics, "Lyrics", class: "form__label" %>
        <%= f.text_area :lyrics, class: "form__input" %>
      </div>

      <div>
        <%= f.submit class: "btn btn__primary" %>
      </div>
    <% end %>
  </div> 
 </div>

app/views/songs/_rating.html.erb
<%= form_with url: song_ratings_path(song), method: :post, data: { controller: "rating", turbo_stream: true }, html: { id: "rating_form_#{song.id}" } do %>

  <div class="flex justify-between">
    <div class="flex gap-2">
      <%= inline_svg "icons/star.svg", class: "h-6 w-6 fill-yellow-300 text-gray-600" %>
      <%= song.average_rating.present? ? "#{number_with_precision(song.average_rating, precision: 1)}/5" : content_tag(:span, "Ще немає оцінок", class: "text-gray-400 italic") %>
    </div>
    <div>
      <% current_rating = song.ratings.find_by(user: current_user)&.rating.to_i %>
      <% 1.upto(5) do |i| %>
        <% star_class = i <= current_rating ? "text-yellow-500" : "text-gray-500" %>
        <%= button_tag type: :submit, name: "rating", value: i,
            class: "text-xl #{star_class}" do %>
            <%= inline_svg "icons/star.svg", class: "h-5 w-5 hover:fill-current hover:text-yellow-500" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/songs/edit.html.erb
<%= render "form", event: @event %>

app/views/songs/index.html.erb
<div class="container mb-20">
    <div class="mb-6">
    <%= form_with url: songs_path, method: :get, local: true, class: "flex items-center gap-4" do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search songs...", class: "search__input" %>
      <%= button_tag "Search", type: "submit", class: "btn btn__blue" %>
      <% if params[:query].present? %>
        <%= link_to "Clear", songs_path, class: "btn btn__secondary" %>
      <% end %>
    <% end %>
  </div>

  <h1 class="text-2xl font-bold mb-4">All Songs</h1>

   <div class="mb-6">
    <%= link_to "+ New Song", new_song_path, class: "btn btn__pink" %>
  </div>
  <% if @songs.any? %>
    <ul class="space-y-4 mb-6">
      <% @songs.each do |song| %>
        <li class="p-4 bg-white shadow rounded-lg">
          <div class="flex justify-between items-center">
            <div>
              <h2 class="text-xl font-semibold text-blue-600">
                <%= link_to song.title, song_path(song), class: "hover:underline" %>
              </h2>
              <p class="text-gray-600">Author: <%= song.author %></p>
              <p class="text-gray-500">Genre: <%= song.genre || "N/A" %></p>
            </div>

            <div class="flex gap-4">
              <%= link_to "Edit", edit_song_path(song), class: "btn btn__primary" %>
              <%= button_to "Delete", song_path(song), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn__pink" %>

            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No songs available.</p>
  <% end %>

</div>

app/views/songs/new.html.erb
<%= render "form", song: @song %>

app/views/songs/show.html.erb
<div class="container max-w-2xl mx-auto p-4 bg-white rounded-xl shadow mb-20">

  <%= render "rating", song: @song %>

  <h1 class="text-2xl font-bold mb-4 text-violet-900 mr-4"><%= @song.title %></h1>  
  <div class="title">Author:
    <span class="text-gray-700 font-medium"><%= @song.author %></span>
  </div>
  <div class="title">Genre:
    <span class="text-gray-700 font-medium"><%= @song.genre.presence || "N/A" %></span>
  </div>
  <div class="title">Lyrics:</div>
  <pre class="bg-gray-100 p-3 rounded whitespace-pre-wrap"><%= @song.lyrics %></pre>

  <div class="flex gap-4 mt-6">
    <%= link_to "Edit", edit_song_path(@song), class: "btn btn__primary" %>
    <%= button_to "Delete", song_path(@song), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?"  }, class: "btn btn__pink" %>
    <%= link_to "Back", songs_path, class: "btn btn__secondary" %>
  </div>
</div>